# Form implementation generated from reading ui file 'D:\kawsar\pc_lock\desktop\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(720, 380))
        MainWindow.setMaximumSize(QtCore.QSize(720, 380))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/CL/.designer/resources/icons/file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidgetScreens = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidgetScreens.setGeometry(QtCore.QRect(0, 0, 1280, 711))
        self.stackedWidgetScreens.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidgetScreens.setObjectName("stackedWidgetScreens")
        self.splash_screen = QtWidgets.QWidget()
        self.splash_screen.setMinimumSize(QtCore.QSize(1000, 1000))
        self.splash_screen.setObjectName("splash_screen")
        self.stackedWidgetScreens.addWidget(self.splash_screen)
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.sidebarWidget = QtWidgets.QWidget(parent=self.homepage)
        self.sidebarWidget.setGeometry(QtCore.QRect(0, 0, 201, 341))
        self.sidebarWidget.setStyleSheet("background-color: #23282c;")
        self.sidebarWidget.setObjectName("sidebarWidget")
        self.sidebarDashboardButton = QtWidgets.QPushButton(parent=self.sidebarWidget)
        self.sidebarDashboardButton.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.sidebarDashboardButton.setFont(font)
        self.sidebarDashboardButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sidebarDashboardButton.setStyleSheet("color: white;\n"
"background-color: rgb(56, 64, 70);\n"
"text-align: left;\n"
"padding-left: 18px;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sidebarDashboardButton.setIcon(icon1)
        self.sidebarDashboardButton.setObjectName("sidebarDashboardButton")
        self.sidebarLogoutButton = QtWidgets.QPushButton(parent=self.sidebarWidget)
        self.sidebarLogoutButton.setGeometry(QtCore.QRect(0, 300, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.sidebarLogoutButton.setFont(font)
        self.sidebarLogoutButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sidebarLogoutButton.setStyleSheet("color: white;\n"
"text-align: left;\n"
"padding-left: 18px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sidebarLogoutButton.setIcon(icon2)
        self.sidebarLogoutButton.setObjectName("sidebarLogoutButton")
        self.widget_3 = QtWidgets.QWidget(parent=self.homepage)
        self.widget_3.setGeometry(QtCore.QRect(170, 0, 551, 441))
        self.widget_3.setStyleSheet("background-color: rgb(35, 40, 30);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 20, 511, 301))
        self.widget_4.setStyleSheet("background-color: rgb(35, 40, 44);\n"
"border: 2px solid rgb(186, 193, 216);")
        self.widget_4.setObjectName("widget_4")
        self.DimTimerWindow = QtWidgets.QPushButton(parent=self.widget_4)
        self.DimTimerWindow.setGeometry(QtCore.QRect(220, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.DimTimerWindow.setFont(font)
        self.DimTimerWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DimTimerWindow.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(186, 193, 216);\n"
"border-radius: 10px;")
        self.DimTimerWindow.setObjectName("DimTimerWindow")
        self.TimerWindowButton = QtWidgets.QPushButton(parent=self.widget_4)
        self.TimerWindowButton.setGeometry(QtCore.QRect(70, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.TimerWindowButton.setFont(font)
        self.TimerWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.TimerWindowButton.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(186, 193, 216);\n"
"border-radius: 10px;")
        self.TimerWindowButton.setObjectName("TimerWindowButton")
        self.MainTimerCounter = QtWidgets.QLabel(parent=self.widget_4)
        self.MainTimerCounter.setGeometry(QtCore.QRect(70, 180, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        self.MainTimerCounter.setFont(font)
        self.MainTimerCounter.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 50px;\n"
"border-radius: 10px;")
        self.MainTimerCounter.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MainTimerCounter.setObjectName("MainTimerCounter")
        self.greet_label = QtWidgets.QLabel(parent=self.widget_4)
        self.greet_label.setGeometry(QtCore.QRect(0, 0, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.greet_label.setFont(font)
        self.greet_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 700 9pt \"Sitka Heading\";\n"
"font-size: 30px;")
        self.greet_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greet_label.setObjectName("greet_label")
        self.ResetTimerButton = QtWidgets.QPushButton(parent=self.widget_4)
        self.ResetTimerButton.setGeometry(QtCore.QRect(330, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.ResetTimerButton.setFont(font)
        self.ResetTimerButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ResetTimerButton.setStyleSheet("background-color: rgb(208, 0, 0);\n"
"color: rgb(186, 193, 216);\n"
"border-radius: 10px;")
        self.ResetTimerButton.setObjectName("ResetTimerButton")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(180, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;\n"
"border: none;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidgetScreens.addWidget(self.homepage)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.widget_2 = QtWidgets.QWidget(parent=self.login_page)
        self.widget_2.setGeometry(QtCore.QRect(-20, 0, 1291, 691))
        self.widget_2.setStyleSheet("background-color: qradialgradient(\n"
"    spread: pad,\n"
"    cx: 0.5,\n"
"    cy: 0.5,\n"
"    radius: 0.5,\n"
"    fx: 0.5,\n"
"    fy: 0.9995,\n"
"    stop: 0.4375 rgba(0, 0, 0, 255),\n"
"    stop: 1 #6766fc\n"
");")
        self.widget_2.setObjectName("widget_2")
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setGeometry(QtCore.QRect(150, 40, 461, 261))
        self.widget.setStyleSheet("background-color: rgb(255, 254, 252)")
        self.widget.setObjectName("widget")
        self.login_email_input = QtWidgets.QLineEdit(parent=self.widget)
        self.login_email_input.setGeometry(QtCore.QRect(70, 80, 321, 31))
        self.login_email_input.setStyleSheet("background-color: #fff;\n"
"border-radius: 15px;\n"
"padding: 2px 8px;\n"
"border: 1px solid rgb(116, 116, 116);\n"
"font-size: 15px;\n"
"\n"
"")
        self.login_email_input.setObjectName("login_email_input")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(90, 70, 71, 16))
        self.label.setStyleSheet("font-size: 15px;")
        self.label.setObjectName("label")
        self.login_password_input = QtWidgets.QLineEdit(parent=self.widget)
        self.login_password_input.setGeometry(QtCore.QRect(70, 140, 321, 31))
        self.login_password_input.setStyleSheet("background-color: #fff;\n"
"border-radius: 15px;\n"
"padding: 2px 8px;\n"
"border: 1px solid rgb(116, 116, 116);\n"
"font-size: 15px;")
        self.login_password_input.setObjectName("login_password_input")
        self.loginButton = QtWidgets.QPushButton(parent=self.widget)
        self.loginButton.setGeometry(QtCore.QRect(70, 200, 321, 31))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginButton.setStyleSheet("background-color: rgb(47, 96, 255);\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"border-radius: 15px;")
        self.loginButton.setObjectName("loginButton")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 130, 71, 16))
        self.label_3.setStyleSheet("font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 25px;")
        self.label_2.setObjectName("label_2")
        self.login_email_input.raise_()
        self.login_password_input.raise_()
        self.loginButton.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.stackedWidgetScreens.addWidget(self.login_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMy_Account = QtWidgets.QMenu(parent=self.menubar)
        self.menuMy_Account.setObjectName("menuMy_Account")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.actionLogout.setIcon(icon)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuMy_Account.addAction(self.actionLogout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMy_Account.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidgetScreens.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MailBlade"))
        self.sidebarDashboardButton.setText(_translate("MainWindow", "Timer"))
        self.sidebarLogoutButton.setText(_translate("MainWindow", "Logout"))
        self.DimTimerWindow.setText(_translate("MainWindow", "Dim Timer"))
        self.TimerWindowButton.setText(_translate("MainWindow", "Timer Window"))
        self.MainTimerCounter.setText(_translate("MainWindow", "Loading . . ."))
        self.greet_label.setText(_translate("MainWindow", "Welcome ---"))
        self.ResetTimerButton.setText(_translate("MainWindow", "Reset Timer"))
        self.label_4.setText(_translate("MainWindow", "Session ending in"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.label_2.setText(_translate("MainWindow", "Login to PC Lock"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMy_Account.setTitle(_translate("MainWindow", "My Account"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
